### ISSUE TITLE
PlugData crashes on arch linux

### ISSUE THREAD

**Issue by aik2mlj** [timothyschoen/PlugData#38]
Hello, I built PlugData from source following the readme. As long as I add an instance of it in REAPER, REAPER just crashes.

**Comment by aik2mlj** [comment]
Also the standalone version can't run as well..

```
./Plugins/Standalone/PlugData
fish: Job 1, './PlugData' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by FlachyJoe** [comment]
I confirm the standalone issue

```
Thread 1 "PlugData" received signal SIGSEGV, Segmentation fault.
0x0000555555cae299 in Connection::getClosestLineIdx (this=0x555556d58830, position=..., plan=std::vector of length 0, capacity 0) at PlugData/Source/Connection.cpp:276
276	        auto line = Line<int>(plan[n - 1], plan[n]);
```

**Comment by timothyschoen** [comment]
Thanks for reporting, I'll check it out. I wrote that function pretty recently, so I guess I made a mistake somewhere! Are you both on Arch btw?

**Comment by FlachyJoe** [comment]
I'm running Xubuntu 21.10 x86_64

**Comment by timothyschoen** [comment]
Fixed it!

Small warning: there have been huge improvements since the last release, and I'm still working to ensure everything's stable. A known issue is that the width of certain objects can sometimes change incorrectly, and there might still be more issues. If you find any, please report them, it helps a lot!

**Comment by aik2mlj** [comment]
Well I'm still experiencing segmentation fault after pulling the newest commits.. Here's the backtrace info
```
#0  0x0000555555a32891 in juce::CharPointer_UTF8::compareIgnoreCase (this=0x18, other=...) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:421
#1  0x00005555559f4beb in juce::String::equalsIgnoreCase (this=0x18, t=...) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_core/text/juce_String.cpp:594
#2  0x0000555555a10239 in juce::XmlElement::hasTagName (this=0x0, possibleTagName=...) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_core/xml/juce_XmlElement.cpp:472
#3  0x0000555555763009 in juce::KeyPressMappingSet::restoreFromXml (this=0x555556bfc800, xmlVersion=...)
    at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_gui_basics/commands/juce_KeyPressMappingSet.cpp:215
#4  0x0000555555c9295c in PlugDataPluginEditor::PlugDataPluginEditor (this=0x555556d12ae0, p=...) at /home/aik2/repos/PlugData/Source/PluginEditor.cpp:39
#5  0x0000555555bb184b in PlugDataAudioProcessor::createEditor (this=0x5555567381b0) at /home/aik2/repos/PlugData/Source/PluginProcessor.cpp:602
#6  0x000055555565372e in juce::AudioProcessor::createEditorIfNeeded (this=0x5555567381b0)
    at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_audio_processors/processors/juce_AudioProcessor.cpp:890
#7  0x000055555560b5ef in juce::PlugDataWindow::MainContentComponent::MainContentComponent (this=0x555556d12950, filterWindow=...)
    at /home/aik2/repos/PlugData/Source/Standalone/PlugDataWindow.h:703
#8  0x000055555560b10e in juce::PlugDataWindow::PlugDataWindow (this=0x555556729cc0, title=..., backgroundColour=..., settingsToUse=0x555556729a40, takeOwnershipOfSettings=false,
    preferredDefaultDeviceName=..., preferredSetupOptions=0x0, constrainToConfiguration=..., autoOpenMidiDevices=false) at /home/aik2/repos/PlugData/Source/Standalone/PlugDataWindow.h:591
#9  0x000055555560ca6f in PlugDataApp::createWindow (this=0x555556710f70) at /home/aik2/repos/PlugData/Source/Standalone/PlugDataApp.cpp:98
#10 0x000055555560cb85 in PlugDataApp::initialise (this=0x555556710f70) at /home/aik2/repos/PlugData/Source/Standalone/PlugDataApp.cpp:104
#11 0x00005555559b3830 in juce::JUCEApplicationBase::initialiseApp (this=0x555556710f70) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:297
#12 0x0000555555764196 in juce::JUCEApplication::initialiseApp (this=0x555556710f70) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_gui_basics/application/juce_Application.cpp:92
#13 0x00005555559b36c4 in juce::JUCEApplicationBase::main () at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:256
#14 0x00005555559b35ec in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffddd8) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:240
#15 0x0000555555607027 in main (argc=1, argv=0x7fffffffddd8) at /home/aik2/repos/PlugData/Libraries/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_Standalone.cpp:47
```

**Comment by timothyschoen** [comment]
Should be fine with pipewire. The problem here is caused by a failure to load the keyboard shortcut preferences, thanks for letting me know! I'll have it fixed very soon!

**Comment by aik2mlj** [comment]
Cool! Also do you mind me adding PlugData to AUR? Would be much more convenient for other arch users in that way :-p

**Comment by timothyschoen** [comment]
I'd like to do that, the only problem is, I've never used arch (I know, embarrassing), so I'll have to read up on it first. And before I do that, I'd like to make sure that crashes like these don't happen anymore!

The bug should be fixed now, let me know if it works or if you have any more problems!

**Comment by aik2mlj** [comment]
Yeah it launched! Thanks for your effort! I mean I can help add PlugData (git version) to AUR if you like ;)

**Comment by timothyschoen** [comment]
I would really appreciate that! You could do it with the current version if you want to, but I expect to fix a lot of issues in the coming weekend, so you could also wait until Monday. I'll leave that up to you :)
